export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as FeatureHighlights } from './FeatureHighlights';
export { default as MainFeatures } from './MainFeatures';
export { default as TechPartners } from './TechPartners';
export { default as PricingPlans } from './PricingPlans';
export { default as CTA } from './CTA';
export { default as Footer } from './Footer';
export { default as CookieBanner } from './CookieBanner';
